### ISSUE TITLE
3 broken links on pyjs.org

### ISSUE THREAD

**Issue by codingisacopingstrategy** [pyjs/original-pyjs#773]
on http://pyjs.org :

http://pyjs.org/Deploy.html
http://pyjs.org/will_and_abe_guide_to_pyjamas.html

on http://pyjs.org/Translator.html :

http://pyjs.org/MigrationGuide.html

**Comment by bittner** [comment]
- Deploy is simply empty (as a Wiki article). Therefore not page is being generated. We could kill the link to it, but I thought there could be content to go into that page sooner or later.
- The "Will and Abe" story can be kicked, I believe. Any objections anyone? Anthony?
- The MigrationGuide link is already fixed in the Wiki and only waits for the website to be regenerated.

**Comment by anthonyrisinger** [comment]
nah no objections at all -- go ahead and remove the references to it and i'll regenerate the site later tonight.

**Comment by bittner** [comment]
Done: Sent Will and Abe to heaven, and killed the Deploy link that lead to no-where-land.

Side Note (for us): It's obviously confusing to have 2 issues lists around, one for source code bugs, the other for the website. We should get rid of https://github.com/pyjs/pyjs.org/issues one day, probably, hmm?
