### ISSUE TITLE
ajax under pyjd/hulahop is broken

### ISSUE THREAD

**Issue by vsevolod127** [pyjs/original-pyjs#778]
Ajax calls under hulahop are working when called from user interaction (such as clicking  button), but are not when called from timer or on application startup. 
Last working version is 33b660a56040f07ea04f54de49706e2e00e57553. 

To try it, start the server: 
`python server.py`
and then client:
`$HOME/pyjs/bin/pyjd client.py`

This is traceback:

```
$HOME/pyjs/bin/pyjd index.py
INFO:pyjs.runners:conf:
[('runner', 'hulahop'),
 ('home', '/home/seva/.pyjd'),
 ('is_desktop', True),
 ('native_dnd', True),
 ('engine', 'hulahop')]
returning /home/seva/.pyjd/prefs.js for key NS_APP_PREFS_50_FILE
loaded
Traceback (most recent call last):
  File "index.py", line 43, in <module>
    main()
  File "index.py", line 40, in main
    test = Test()
  File "index.py", line 17, in __init__
    self.makeAjaxCall()
  File "index.py", line 21, in makeAjaxCall
    self.svc.echo(self, 'test arg')
  File "/home/seva/byhr/env/pyjs/library/pyjamas/JSONService.py", line 259, in __call__
    params, handler)
  File "/home/seva/byhr/env/pyjs/library/pyjamas/JSONService.py", line 141, in sendRequest
    self.headers):
  File "/home/seva/byhr/env/pyjs/library/pyjamas/HTTPRequest.py", line 37, in asyncPost
    returnxml, content_type, headers)
  File "/home/seva/byhr/env/pyjs/library/pyjamas/HTTPRequest.py", line 182, in asyncImpl
    res = xmlHttp.open(method, url)
  File "<XPCOMObject method 'open'>", line 3, in open
xpcom.Exception: -1041039359 (NS_ERROR_NOT_INITIALIZED)
```

This is client.py:

``` python
import pyjd # this is dummy in pyjs.
from pyjamas.ui.HTML import HTML
from pyjamas.ui.Button import Button
from pyjamas.ui.RootPanel import RootPanel
from pyjamas.Timer import Timer
from pyjamas.JSONService import JSONProxy


class Test:

    def __init__( self ):
        self.svc = JSONProxy('svc', ['echo'])
        RootPanel().add(Button('make ajax call', self.makeAjaxCall))
        RootPanel().add(Button('make ajax call after 1s', self.scheduleCall))
        self.makeAjaxCall()
        self.scheduleCall()

    def makeAjaxCall( self, *args, **kw ):
        self.svc.echo(self, 'test arg')

    def scheduleCall( self, *args ):
        Timer(notify=self.makeAjaxCall, delayMillis=1000)

    def onRemoteResponse( self, response, request_info ):
        print 'server responded: %r' % response

    def onRemoteError( self, code, errobj, request_info ):
        message = errobj['message']
        if code != 0:
            print "HTTP error %d: %s" % (code, message)
        else:
            code = errobj['code']
            "JSONRPC Error %s: %s" % (code, message)


def main():
    pyjd.setup("http://localhost:8080/index.html")
    test = Test()
    pyjd.run()

main()
```

This is server.py (minimal jsonrpc server implementation):

``` python
#!/usr/bin/env python

import json
import BaseHTTPServer
import SimpleHTTPServer


class Handler(SimpleHTTPServer.SimpleHTTPRequestHandler):

    def do_POST( self, *args, **kw ):
        cl = int(self.headers['Content-Length'])
        request = json.loads(self.rfile.read(cl))
        id = request['id']
        arg0 = request['params'][0]
        self.log_message('post#%s: %r' % (id, arg0))
        result = 'from server: %r' % arg0
        resp = dict(result=result, error=None, id=id)
        self.send_response(200)
        self.end_headers()
        self.wfile.write(json.dumps(resp))
        self.wfile.flush()


http = BaseHTTPServer.HTTPServer(('', 8080), Handler)
http.serve_forever()
```

**Comment by keesbos** [comment]
I noticed that when you checkout the working commit, do a bootstrap and advance to the HEAD, it works. If you do a bootstrap in the HEAD, it doesn't.

**Comment by vsevolod127** [comment]
I run the following commands for checkout:

```
git checkout <revision>
find -name '*.pyc' | xargs rm
python bootstrap.py
```

What do you mean by "advance to the HEAD"?

**Comment by keesbos** [comment]
This works:
$ git pull --rebase
$ git checkout 33b660a56040f07ea04f54de49706e2e00e57553
$ ./bootstrap.py
$ git checkout master

This not:
$ git checkout master
$ ./bootstrap.py

This narrows the search to the differences in pyjd/**init**.py.in

**Comment by vsevolod127** [comment]
Do not forget to remove all *.pyc files after checkout:

```
git checkout 33b660a
find -name '*.pyc' | xargs rm
python bootstrap.py
# now it works
git checkout master
find -name '*.pyc' | xargs rm
python bootstrap.py
# now it is broken
git checkout 33b660a
find -name '*.pyc' | xargs rm
python bootstrap.py
# now it works again
```

**Comment by keesbos** [comment]
You're right.

```
git checkout 33b660a
find -name '*.pyc' | xargs rm
python bootstrap.py
git checkout master
# now is doesn't work, even when changing 'from hula import *' to 'from pyjs.runners.hula import *' and 'import importers' to 'from pyjs.runners import importers'
```

So, its not just the pyjd/**init**.in

**Comment by anthonyrisinger** [comment]
use:

```
git checkout XYZ
git clean -fdx
```

... git clean will blow away absolutely every file (and with -d, directory) that git does not track... it's how you return to a pristine state.  be careful with it ;-)

**Comment by anthonyrisinger** [comment]
my guess is e7347818a8dbf9b267b0dc2c5e4e21541483c803

... since that crap completely botches ("hides") like 4 modules, including gtk and gobject... that stuff makes the introspection bindings cry... a lot.  took me some time to realize what was happening (thats pygtk stuff, which is for all intents and purposes, dead).

could also be the "this looks useless" part of 51efc7bbd5d3ed9e6aab95e3b258020aa47cbe3c ... LMK.

we may have to find a better way to be selective, if either turns out to be related.

**Comment by keesbos** [comment]
OK. Got it going. Two fixes:
1. Postponed the "if parts[0] not in ('pyjamas',):" int imputil.py to after checking th context and do this only if the context is None.
2. Fixed the **init** of XULrunnerHackCallback in HTTPRequest.hulahop.py. The 
   "pyjd.add_timer_queue(self.callback)" failed and is now replaced with "from pyjs.runners import hula" and "hula.add_timer_queue(self.callback)".

Ad. 1. I'm not sure if this exclude is a good idea. If you've got a library other than pyjamas and you need this behavior, you're stuck.

Ad 2. I think it would be better to retrieve the engine module from pyjd, e.g. pyjd.get_runner(), or pyjd.manager.get_runner().

What do you think?

**Comment by anthonyrisinger** [comment]
your probably right about the exclude bits, as there may be people using overrides in their own pyjs projects, and since they are not in the pyjamas namespace they'd be excluded ...

first off, since the importer tools we use are dead, we'd have more flexibility if we instead used a [PEP 302](http://www.python.org/dev/peps/pep-0302/) path_hook or Finder/Loader (since python 2.3) -- if no overrides exist we'd fallback to standard `__import__` -- it would essentially perform the same function but with less complication and within the stdlib.

... another option that isn't terrible in my mind is requiring packages to "opt-in" somehow ... either way, i think it's better to err on the side of caution, and avoid over-zealous import trickery.

as for 2, my goal was actually to eliminate the pyjd module altogether (that's why it's only a stub basically) ... i don't think people should have to import it or care about it at all.  i reeeeally like the idea of making the `pyjs` module executable via [runpy/**main**](http://docs.python.org/library/runpy.html) and requiring users to start their apps through that.  this gives pyjs the opportunity to do any initialization before any user code is even imported.

... eg. something like:

```
# python -m pyjsr MyModule.py
```

... see any issues with that? (on a side note i think `pyjd` is a confusing name... and looks funny too :-) much prefer something fresh like "pyjs-realtime" which is more accurate [contrasting the realtime bindings vs. translation])

if this bug is complete, lets close it out and open a specific ticket to discuss options, or take to the ML.  i'll let one of you close though because i can't confirm... i'll try the GI bindings soon to make sure they didnt break (it's normally imported like `from gi.repository import WebKit`... it's a magic module, not sure it can be imported directly)
